Repository utopia-rise/kotlin-godot-wrapper, pull requests merged in 2020-01, with the labels that each got.

#8 Update documentation
  API_DIFFERENCES.md
  COMPILING.md
  COMPILING_FROM_SOURCE.md
  GETTING_STARTED.md
  README.md
  REGISTRATION.md
Labels: documentation

#11 Add basis of entry generating annotation processor
  settings.gradle.kts
  tools/annotations/build.gradle.kts
  tools/annotations/src/commonMain/kotlin/org/godotengine/kotlin/annotation/Register.kt
  tools/godot-annotation-processor/build.gradle.kts
  tools/godot-annotation-processor/src/main/kotlin/org/godotengine/kotlin/annotationprocessor/AnnotationProcessorExtensions.kt
  tools/godot-annotation-processor/src/main/kotlin/org/godotengine/kotlin/annotationprocessor/RegisterAnnotationProcessor.kt
  tools/godot-annotation-processor/src/main/resources/META-INF/gradle/incremental.annotation.processors
  tools/godot-annotation-processor/src/main/resources/META-INF/services/javax.annotation.processing.Processor
Labels: feature, tools:annotationProcessor, tools:annotations

#16 Feature/rework api code generation
  gradle.properties
  tools/api-classes-generator/build.gradle.kts
  tools/api-classes-generator/src/main/kotlin/Argument.kt
  tools/api-classes-generator/src/main/kotlin/Class.kt
  tools/api-classes-generator/src/main/kotlin/Enum.kt
  tools/api-classes-generator/src/main/kotlin/Generator.kt
  tools/api-classes-generator/src/main/kotlin/Graph.kt
  tools/api-classes-generator/src/main/kotlin/ICall.kt
  tools/api-classes-generator/src/main/kotlin/Method.kt
  tools/api-classes-generator/src/main/kotlin/Property.kt
  tools/api-classes-generator/src/main/kotlin/Signal.kt
  tools/api-classes-generator/src/main/kotlin/TypeCast.kt
  tools/godot-annotation-processor/build.gradle.kts
Labels: client:linux, client:macOS, client:windows, enhancement
